config/routes.rb
Rails.application.routes.draw do
  root 'pages#welcome'
  get 'pages/welcome'

  resources :favorites
  resources :ratings
  resources :users do
    collection do
      get :search
      post :results
    end
  end
  resources :sitters
  resources :pets
  resources :sit_pets


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get    '/auth/:provider'          => 'omniauth#auth',    as: :auth
  get    '/auth/:provider/callback' => 'session#create'
  get    '/auth/failure'            => 'session#failure'

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  get '/logout' => 'session#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
end

app/models/pet.rb
class Pet < ApplicationRecord
  belongs_to :user
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :user
  attachment :image
end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :user
  RATINGS = [["", 0],["⭐", 1],["⭐⭐", 2],["⭐⭐⭐", 3],["⭐⭐⭐⭐", 4],["⭐⭐⭐⭐⭐", 5]]
end

app/models/sit_pet.rb
class SitPet < ApplicationRecord
  belongs_to :user, required: false
end

app/models/sitter.rb
class Sitter < ApplicationRecord
  has_many :photos
  has_many :pets
  has_many :sit_pets
  has_many :favorites
  has_many :ratings
  attachment :picture
  accepts_nested_attributes_for :pets
  accepts_nested_attributes_for :sit_pets
end

app/models/user.rb
class User < ApplicationRecord

  has_many :sitters, through: :favorites
  has_many :photos
  has_many :pets
  has_many :sit_pets
  has_many :favorites
  has_many :ratings
  attachment :picture
  accepts_nested_attributes_for :sit_pets

  geocoded_by :full_street_address   # can also be an IP address
  after_validation :geocode          # auto-fetch coordinates

  def full_street_address
    [address, city, state, zip].join(", ")
  end

  # Factory method to create a user from some omniauth data
  # Omniauth will use this to build a *NEW* user for us
  def self.from_omniauth(authentication_data)
    user = User.where(provider: authentication_data['provider'],
                      uid: authentication_data['uid']).first_or_create

    Rails.logger.debug "The user is #{user.inspect}"

    user.name         = authentication_data.info.name
    user.nickname     = authentication_data.info.nickname
    user.access_token = authentication_data.info.access_token

    user.save!

    Rails.logger.debug "After saving, the user is #{user.inspect}"

    return user
  end
  def self.nearby(latitude, longitude)
    User.near([latitude, longitude], 40)
  end

  def self.categorize(sitters)
    dog_sitters = sitters.includes(:sit_pets).where("sit_pets.pet_kind" => "dog").distinct
    cat_sitters = sitters.includes(:sit_pets).where("sit_pets.pet_kind" => "cat").distinct
    other_sitters = sitters.includes(:sit_pets).where("sit_pets.pet_kind" => "other").distinct
    multi_sitters = dog_sitters & cat_sitters & other_sitters

    return [dog_sitters, cat_sitters, other_sitters, multi_sitters]
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  layout false
  def welcome
  end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  # GET /pets
  def index
    @pets = Pet.all
  end

  # GET /pets/1
  def show
    @pet = Pet.find(params[:id])
  end

  # GET /pets/new
  def new
    @pet = Pet.new
  end

  # GET /pets/1/edit
  def edit
    @pet = Pet.find(params[:id])
  end

  # POST /pets
  def create
    @pet = Pet.new(pet_params)

    if @pet.save
      redirect_to @pet, notice: 'Pet was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /pets/1
  def update
    @pet = Pet.find(params[:id])
    if @pet.update(pet_params)
      redirect_to @pet, notice: 'Pet was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /pets/1
  def destroy
    @pet = Pet.find(params[:id])
    @pet.destroy
    redirect_to pets_url, notice: 'Pet was successfully destroyed.'
  end

  private
    # Only allow a trusted parameter "white list" through.
    def pet_params
      params.require(:pet).permit(:pet_kind, :breed, :size, :user_id)
    end
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  # GET /ratings
  def index
    @ratings = Star.all
    @ratings = @ratings.where(star: params[:star]) if params[:star].present?
  end

  # GET /ratings/1
  def show
    @rating = Rating.find(params[:id])
  end

  # GET /ratings/new
  def new
    @rating = Rating.new
  end

  # GET /ratings/1/edit
  def edit
    @rating = Rating.find(params[:id])
  end

  # POST /ratings
  def create
    @rating = Rating.new(rating_params)

    if @rating.save
      redirect_to @rating, notice: 'Rating was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /ratings/1
  def update
    @rating = Rating.find(params[:id])
    if @rating.update(rating_params)
      redirect_to @rating, notice: 'Rating was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /ratings/1
  def destroy
    @rating = Rating.find(params[:id])
    @rating.destroy
    redirect_to ratings_url, notice: 'Rating was successfully destroyed.'
  end

  private
    # Only allow a trusted parameter "white list" through.
    def rating_params
      params.require(:rating).permit(:star, :user_id, :sitter_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate!, except: [:index, :results, :search]
  # GET /users
  def index
    @users = User.all

    @latitude  = params[:latitude]
    @longitude = params[:longitude]
    if @latitude && @longitude
      users = User.nearby(@latitude, @longitude)

    else
      users = @users
    end

    @dog_sitters, @cat_sitters, @other_sitters, @multi_sitters = User.categorize(users)
  end

  # GET /users/1
  def show
    if params[:id].to_i == 0
      redirect_to search_users_path
      return
    end

    @user = User.find(params[:id])
  end

  # GET /users/new
  def new
    @user = User.new
    @user.sit_pets.build
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to @user, notice: 'User was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /users/1
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  def search
  end

  def signin
  end

  def results
    @users = User.all
    if params[:ratings].present?
      @users = @users.includes(:ratings).where("ratings.star" => params[:ratings])
    end

    if (params[:city].blank? || params[:state].blank?) && params[:zip].blank?
      redirect_to search_users_path, :flash => { :notice => "Please enter City and State or Zip code to search for sitter" }
      return
    else
      location = [params[:city], params[:state], params[:zip]].compact.join(',')
    end

    if params[:size_dog].present?
      @users = @users.includes(:sit_pets).where("sit_pets.size" => params[:size_dog])
    end

    # All other work is done, finally just find the nearby users
    nearby_users = @users.near(location, 20)

    @results = nearby_users

    # Limit the search to only the kinds of pets the user checked
    Array(params[:pet_kind]).each do |kind|
      # The users are the exist users who also sit this kind of pet
      @results = @results & @users.includes(:sit_pets).where("sit_pets.pet_kind" => kind)
    end

    render :results
  end

  # DELETE /users/1
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_url, notice: 'User was successfully destroyed.'
  end

  private
    # Only allow a trusted parameter "white list" through.
    def user_params
      params.require(:user).permit(:name, :address, :city, :state, :zip, :phone, :email, :picture, :about_me, :backyard, :preferences, pets_attributes:[:pet_kind, :breed, :size], sit_pets_attributes: [:breed, :pet_kind, :size, :pet_number])

    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
  def star_rating(star)
    if star.nil? || star <= 0
      "NA"
    else
      "⭐" * [star,5].min
    end
  end
end

app/helpers/sit_pets_helper.rb
module SitPetsHelper
end

app/helpers/sitters_helper.rb
module SittersHelper
end

app/helpers/users_helper.rb
module UsersHelper

end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{charset: "utf-8"}
    %meta{content: "IE=edge", "http-equiv" => "X-UA-Compatible"}
    %meta{:content => "width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no", :name => "viewport"}
    %meta{content: "", name: "description"}
    %meta{content: "", name: "author"}
    %title
      = InstaPetSitter

    / HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries
    /[if lt IE 9]
      = javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js"

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body{class: "controller-#{controller_name} action-#{action_name}"}
    %nav.navbar.navbar-inverse.navbar-fixed-top.jasmine{role: "navigation"}
      .container-fluid
        .navbar-header
          %button.navbar-toggle.collapsed{type: "button", data: {toggle: "collapse", target: "#navbar"}, aria: {expanded: "false", controls: "navbar"} }
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          = link_to root_path, class: "navbar-brand" do
            = image_tag("logoCap2.png", size: '275x35', class: "logo-wel")
        #navbar.collapse.navbar-collapse
          %ul.nav.navbar-nav.navbar-right.menu_cap
            %li.menu
              = link_to "Search Sitters", search_users_path # This will have two options like the cover page and lead to either
            %li.menu
              = link_to "Nearby Sitters", users_path, class: "nearby-sitter-nav"
            %li.menu
              = link_to "Become A Sitter", new_user_path
            %li.menu
              = link_to "Paw Necessities", ""

            - if logged_in?
              %li.menu
                = link_to "SIGN OUT", logout_path
            - else

              %li.menu
                = link_to "SIGN IN", login_path
                  
        / /.navbar-collapse
      / /.container-fluid


  - flash.each do |name, msg|
    = content_tag :div, class: "alert alert-#{name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do
      %button.close{type: "button", data: {dismiss: "alert"} }
        %span{aria: {hidden: "true"} } &times;
        %span.sr-only Close
      = msg
= yield

app/views/pages/welcome.html.haml
!!!
%html
  / FROM: https://css-tricks.com/should-i-use-a-video-as-a-background/
  %head
    %meta{charset: "utf-8"}
    %meta{content: "IE=edge", "http-equiv" => "X-UA-Compatible"}
    %meta{content: "width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no", name: "viewport"}
    %meta{content: "", name: "description"}
    %meta{content: "", name: "author"}
    %title
      = InstaPetSitter

    / HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries
    /[if lt IE 9]
      = javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js"

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

%body
  %nav.navbar.transparent.navbar-inverse.navbar-fixed-top{role: "navigation"}
    .container-fluid
      .navbar-header.welcome
        %button.navbar-toggle.collapsed{type: "button", data: {toggle: "collapse", target: "#navbar"}, aria: {expanded: "false", controls: "navbar"} }
          %span.sr-only Toggle navigation
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
      = link_to root_path, class: "navbar-brand" do
        = image_tag("logoCap2.png", size: '275x35', class: "logo-wel")
      #navbar.collapse.navbar-collapse.font_wireframe
        %ul.nav.navbar-nav.navbar-right.menu_cap
          %li.menu
            = link_to "Search Sitters", search_users_path # This will have two options like the cover page and lead to either
          %li.menu
            = link_to "Nearby Sitters", users_path, class: "nearby-sitter-nav"
          %li.menu
            = link_to "Become A Sitter", new_user_path
          %li.menu
            = link_to "Paw Necessities", "#"

          - if logged_in?
            %li.menu
              = link_to "SIGN OUT", logout_path
          - else

            %li.menu
              = link_to "SIGN IN", login_path

  = video_tag("french.mp4", :autoplay => true, :playsinline => true, :loop => true, poster: "french.jpg", class: "bgvid")

  / These scripts are optional if you want click-to-pause
  %script{:src => "http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"}
  .container
    .search
      .row.search-buttons
        .col-md-4.col-md-offset-2.each_button
          = link_to search_users_path, class: "btn btn-labeled default find-sitter" do
            Find a Sitter &nbsp
            %span.btn-label
              %i.glyphicon.glyphicon-search

        .col-md-4.each_button
          = link_to users_path, class: "btn btn-labeled default nearby-sitter" do
            Nearby Sitter Now &nbsp
            %span.btn-label
              %i.glyphicon.glyphicon-search